### ISSUE TITLE
连基本的使用也没写？

### ISSUE THREAD

**Issue by callmesoul** [Javen205/TNW#1]
连基本的使用文档呢？
跑起来不知道干嘛

**Comment by Javen205** [comment]
@callmesoul 文档有时间了就会写，先参考Demo 

以 `Nest`  Demo 为例：
`/msg` 的 `get` 请求就是验证开发者服务器，开启开发者模式，  `post` 请求就是公众号与微信服务器各种数据的交互(比如文本消息等)，各种消息处理在 `MsgController ` 里面

`/jssdk ` 就是微信JS-SDK使用案例
`/toAuth` 就是微信授权登录，`/auth` 为授权回调
其他就是常用接口了 比如 发送模板消息 `/sendTemplate ` 等

**Comment by Javen205** [comment]
文章会陆续发到这里 [TNW 开发微信公众号系列文章](https://github.com/Javen205/TNW/wiki/TNW-%E5%BC%80%E5%8F%91%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7%E7%B3%BB%E5%88%97%E6%96%87%E7%AB%A0)
