### ISSUE TITLE
其他功能有上线计划吗？

### ISSUE THREAD

**Issue by zuohuadong** [Javen205/TNW#2]
路线图里列举的功能

**Comment by Javen205** [comment]
最近工作调整比较忙，会先写 `TNW` 接入文章(最近吐槽没有对接文档的人比较多/(ㄒoㄒ)/~~，我会继续更新的)。系列文章 [点击这里查看](https://github.com/Javen205/TNW/wiki/TNW-%E5%BC%80%E5%8F%91%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7%E7%B3%BB%E5%88%97%E6%96%87%E7%AB%A0)

小程序、支付、小游戏接口的支持目前时间待定

**Comment by Javen205** [comment]
@zuohuadong 已支持微信支付
